run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  revive:
    rules:
      # Disable style-only rules that don't affect code quality
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: exported
        disabled: true
